name: template
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.9
    # latest version of plotly can be found at https://github.com/plotly/plotly.py/releases .
    # Version is hardcoded to ensure uniformity no matter the platform.
  - plotly=5.5.0
  - pandas=1.3
  - dash=2.0
  - pytest=6.2
  - pylint=2.12
  - black=21.12b0
  - black-jupyter=21.12b0
  - pip=21.3.1
  - numpy=1.22.1


  # The version pinning here needs to match the version of Chrome installed inside of
  # AWS Workspaces
  - python-chromedriver-binary>=96,<97

  # These dependencies come from https://github.com/plotly/dash/blob/dev/requires-testing.txt
  # They should be installed as part of dash[testing], but the conda-forge package for dash
  # does not declare them as dependencies.
  # See issue in conda-forge GitHub org: https://github.com/conda-forge/dash-feedstock/issues/100
  - beautifulsoup4=4.10
  - lxml=4.6
  - percy=2.0
  - requests=2.26
  - selenium=3.141
  - waitress=2.0
  - webdriver-manager
